version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: php-app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-web
    volumes:
      - ./app:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4987:80"
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
